### ISSUE TITLE
Box shadow

### ISSUE THREAD

**Issue by FrankOHara43** [zeno-918/Simon-Game-#2]
<h3>Description</h3>
currently over hovering there is no shadow.

<h3>Expected Behavior</h3>
shadow effect. 

![Screenshot 2024-10-06 175504](https://github.com/user-attachments/assets/89aec52e-8387-479b-9a23-e470fa689d37)

**Comment by sujalcharati** [comment]
Please assign this issue to me under hacktoberfest.

**Comment by FrankOHara43** [comment]
@zeno-918 take a look at this pr.

**Comment by FrankOHara43** [comment]
done.
